version: '3.4'

services:
  divartelegrambot:
    image: divartelegrambot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
        - ./.env
    volumes:
      - ./:/app